apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.200-172.18.255.250 # Burayı kendi subnetine göre güncelle!
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty-advertisement
  namespace: metallb-system